name: Official Release

on:
  push:
    tags:
      - 'v*'  # 仅当推送 v1.2.3 格式标签时触发

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract Version from Tag
        id: tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Tag: ${TAG_NAME} → Version: ${VERSION}"

      - name: Build and Publish
        run: ./gradlew publish -Pversion=${{ steps.tag.outputs.version }} --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## ✨ Official Release ${GITHUB_REF_NAME}
            - Published automatically via CI/CD
          files: |
            build/libs/*-all.jar
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}